# Generated by Django 3.1.2 on 2023-07-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarrito',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='productocarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='ProductoCarrito',
        ),
    ]
