# Generated by Django 3.1.2 on 2023-07-07 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orden_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
